from .LessonCreate import LessonCreatAPIView
from .CommentCreate import CommentCreatAPIView
from .CommentDelete import CommentDeleteAPIView
from .CategoryDelete import CategoryDeleteAPIView
from .CategoryList import CategoryListAPIVIew
from .LessonList import LessonListAPIVIew
from .CategoryCreate import CategoryCreatAPIView
from .CourseList import CourseListAPIVIew
from .CommentList import CommentListAPIVIew
from .WebinarList import WebinarListAPIVIew
from .LessonDelete import LessonDeleteAPIView
from .CourseDelete import CourseDeleteAPIView
from .LessonUpdate import LessonUpdateAPIView
from .CourseUpdate import CourseUpdateAPIView
from .WebinarDelete import WebinarDeleteAPIView
from .WebinarUpdate import WebinarUpdateAPIView
from .CourseCreate import CourseCreatAPIView
from .WebinarCreate import WebinarCreatAPIView
from .ModuleList import ModuleListAPIVIew
from .ModuleDelete import ModuleDeleteAPIView
from .ModuleUpdate import ModuleUpdateAPIView
from .ModuleCreate import ModuleCreatAPIView