# Generated by Django 5.2.3 on 2025-08-17 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('card_token', models.CharField(max_length=255, verbose_name='Card token')),
                ('cardholder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cardholder name')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='Last four digits')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
                ('expire_month', models.CharField(max_length=2, verbose_name='Expire month')),
                ('expire_year', models.CharField(max_length=4, verbose_name='Expire year')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is confirmed')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.provider', verbose_name='Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserCard',
                'verbose_name_plural': 'UserCards',
            },
        ),
    ]
